version: '3.3'

services:
  enshrouded:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    volumes:
      - "enshrouded_data:/home/steam/enshrouded"
    networks:
      - "backendnetwork"
    environment:
      - "ENSHROUDED_SERVER_NAME=puretascanosos"
      - "ENSHROUDED_SERVER_PASSWORD=4769"
      - "ENSHROUDED_SERVER_MAXPLAYERS=16"

volumes:
  enshrouded_data:

networks:
  backendnetwork:
    attachable: true
